const CompanyNameList=[
  'Company Not Listed',
'21st Century',
'AAA',
'AABCO',
'AARP',
'Access Insurance',
'Acordia',
'Aegis Security',
'AETNA',
'Affirmative',
'AFLAC',
'AHCP',
'AIG',
'AIU',
'Alfa Insurance',
'All Nation',
'All Risk',
'Allianz',
'Allied',
'Allstate',
'American Alliance',
'American Automobile Insurance',
'American Banks',
'American Casualty',
'American Community',
'American Deposit Insurance',
'American Direct Business Insurance',
'American Economy',
'American Empire Insurance',
'American Equity',
'American Family',
'American Financial',
'American Health Underwriters',
'American Home Assurance',
'American Insurance',
'American International',
'American International Pacific',
'American International South',
'American Manufacturers',
'American Mayflower Insurance',
'American Medical Securities',
'American Motorists Insurance',
'American National',
'American National Property and Casualty',
'American Premier',
'American Protection Insurance',
'American Reliable',
'American Republic',
'American Savers Plan',
'American Service Insurance',
'American Skyline Insurance Company',
'American Spirit Insurance',
'American Standard',
'American States',
'America\'s Ins. Consultants',
'AmeriPlan',
'Amerisure',
'Amerus',
'Amica',
'Answer Financial',
'Anthem',
'API',
'Arbella',
'Arizona General',
'Armed Forces Insurance',
'Assigned Risk',
'Associated Indemnity',
'Associated Insurance Managers',
'Assurant',
'Atlanta Casualty',
'Atlanta Specialty',
'Atlantic Indemnity',
'Atlantis',
'Austin Mutual',
'Auto Club Insurance Company',
'Auto Owners',
'Aviva',
'Avomark',
'AXA Advisors',
'Badger Mutual',
'Bankers & Shippers',
'Bankers Life and Casualty',
'Banner Life',
'Best Agency USA',
'Blue Cross',
'Blue Cross / Blue Shield',
'Blue Shield of California',
'Bonneville',
'Boston Old Colony',
'Brooke Insurance',
'Builders',
'Cal Farm Insurance',
'California Casualty',
'California State Automobile Association',
'Camden',
'Capital Choice',
'Care Entr?e',
'Cascade National Ins',
'Casualty Assurance',
'Celtic Insurance',
'Centennial',
'Charter Oak',
'Chase Insurance Group',
'Chesapeake',
'Chicago Insurance',
'Chubb',
'Church Mutual',
'Cigna',
'Citizens',
'Clarendon',
'Clarendon National Insurance',
'Cloverleaf',
'CNA',
'Colonial',
'Combined',
'Commercial Union',
'Commonwealth',
'Comparison Market',
'Continental',
'Continental Casualty',
'Continental Divide Insurance',
'Cotton States',
'Cottonwood',
'Country Financial',
'Country Insurance and Financial Services',
'Countrywide',
'Credit Union',
'Criterion',
'CSE Insurance Group',
'CUNA Mutual',
'Dairyland',
'Dakota Fire',
'Deerbrook',
'Depositors Emcasc',
'Dixie',
'Eastwood Insurance',
'Ebco General',
'Economy',
'Economy Fire & Casualty',
'Economy Preferred',
'eFinancial',
'eHealth',
'Electric Insurance',
'Elephant',
'EMC',
'Empire',
'Employers Fire',
'Ensure',
'Equitable Life',
'Erie',
'Esurance',
'Explorer',
'F&G Life',
'Facility',
'Farm and Ranch',
'Farm Bureau',
'Farm Bureau St. Pau',
'Farmers',
'Farmers Union',
'Farmland',
'Federal',
'Federated',
'Fidelity Insurance Company',
'FinanceBox.com',
'Financial Indemnity',
'Fire and Casualty Insurance Co of CT',
'Firemans Fund',
'First Acceptance Insurance',
'First American',
'First Financial',
'First General',
'First National',
'Ford Motor Credit',
'Foremost',
'Foresters',
'Fort Dearborn Life',
'Fortis',
'Franklin',
'Freedom Health',
'Geico',
'General Accident',
'General Insurance',
'Genworth Financial',
'Germania Insurance',
'Globe',
'GMAC',
'Golden Rule (map to United Healthcare)',
'Golden Rule Insurance',
'Government Employees',
'Grange',
'GRE Harleysville H',
'Great American',
'Great Way',
'Great West',
'Grinnell Mutual',
'Guaranty National',
'Guardian',
'Guide One',
'Halcyon',
'Hanover Lloyd\'s Insurance Company',
'Happy Days',
'Hartford',
'Hartford AARP',
'Harvard Pilgrim',
'Hawkeye Security',
'Health Benefits Direct',
'Health Care Solutions',
'Health Choice One',
'Healthmarkets',
'Health Net',
'Health Plus of America',
'HealthShare American',
'Heritage',
'High Point Insurance',
'Homeinsurance',
'Homeland Health',
'Horace Mann',
'Humana',
'IAB',
'IDS',
'IFA Auto Insurance',
'IGF',
'IIS Insurance',
'Independent',
'ING',
'Infinity',
'InSphere',
'Insur. of Evanston',
'Insurance Insight',
'Insurance.com',
'Integon',
'Interstate',
'Investors Life',
'John Deere',
'John Hancock',
'Kaiser Foundation Health Plan',
'Kaiser Permanente',
'Kemper',
'Kentucky Central',
'Landmark American Insurance',
'Leader Insurance',
'League General',
'Liberty Insurance Corp',
'Liberty Mutual',
'Liberty National',
'Liberty Northwest',
'LifeWise Health Plan',
'Lincoln Benefit Life',
'LTC Financial Partners',
'Lumbermens Mutual',
'Mapfre',
'Marathon',
'Markel American',
'Maryland Casualty',
'Mass Mutual',
'Matrix Direct',
'MEGA Life and Health',
'Mega/Midwest',
'Mendota',
'Merastar',
'Mercury',
'MetLife',
'Metropolitan Insurance Co.',
'Mid Century Insurance',
'Mid-Continent',
'Middlesex Insurance',
'Midland National Life',
'Mid-West National Life Insurance',
'Midwest Mutual',
'Millbank',
'Millers Mutual',
'Milwaukee',
'Milwaukee General',
'Milwaukee Guardian',
'Milwaukee Mutual',
'Minnehoma',
'Missouri General',
'Modern Woodmen of America',
'Monumental Life Insurance',
'Mony Group',
'Mortgage Protection Bureau',
'Motors',
'Mountain Laurel',
'MSI Insurance',
'Mutual Insurance',
'Mutual Of Enumclaw',
'Mutual of New York',
'Mutual Of Omaha',
'Nacolah',
'National Alliance',
'National Ben Franklin Insurance',
'National Casualty',
'National Colonial',
'National Continental',
'National Health Insurance',
'National Fire Insurance Company of Hartford',
'National Indemnity',
'National Insurance',
'National Merit',
'National Surety Corp',
'National Union Fire Insurance',
'National Union Fire Insurance of LA',
'National Union Fire Insurance of PA',
'Nationwide',
'Nat\'l Farmers Union',
'New England Financial',
'New York Life',
'North American',
'North Pacific',
'North Pointe',
'North Shore',
'Northern Capital',
'Northern States',
'Northland',
'Northwest Pacific',
'Northwestern',
'Northwestern Mutual',
'Northwestern Mutual Life',
'Northwestern Pacific Indemnity',
'NuStar Insurance',
'Ohio Casualty',
'Ohio Security',
'Olympia',
'Omaha',
'Omni Ins.',
'Omni Insurance',
'Oregon Mutual',
'Orion Ins.',
'Orion Insurance',
'Other',
'Oxford Health Plans',
'PacifiCare',
'Pacific Indemnity',
'Pacific Insurance',
'Pafco',
'Paloverde',
'Patriot General',
'Peak Property and Casualty Insurance',
'Pekin Insurance',
'Pemco',
'Penn America',
'Penn Mutual',
'Pennsylvania Natl',
'Phoenix',
'Physicians',
'Pinnacle',
'Pioneer Life',
'PJP Agency',
'Plymouth Rock',
'Preferred Abstainers',
'Preferred Mutual',
'Premier',
'Prestige',
'Primerica',
'Principal Financial',
'Progressive',
'Protective Life',
'Provident',
'Prudential',
'Quality',
'Ramsey',
'Ranger',
'RBC Liberty',
'RBC Liberty Insurance',
'Regal',
'Reliance',
'Reliant',
'Republic Indemnity',
'Response Insurance',
'Rockford Mutual',
'Rodney D. Young',
'Safeco',
'Safeguard',
'Safeway',
'Sammons Insurance',
'Sea West Insurance',
'Secura',
'Security Insurance',
'Security National',
'Sedgwick James',
'Sentinel Insurance',
'Sentry',
'Shelter',
'Skandia TIG Tita',
'Spectrum',
'St. Paul',
'Standard Fire Insurance Company',
'Standard Guaranty',
'State and County Mutual Fire Insurance',
'State Auto',
'State Farm',
'State Mutual',
'State National',
'Sun Coast',
'Superior',
'Superior Guaranty Insurance',
'Sure Health Plans',
'Sutter',
'The Ahbe Group',
'The Annexus Group',
'The Credo Group',
'The General',
'TICO Insurance',
'TIG Countrywide Insurance',
'Time Insurance',
'Titan',
'Total',
'Tower',
'TransAmerica',
'Travelers',
'Trinity Universal',
'Tri-State Consumer',
'Trust Hall',
'Tufts Health Plan',
'Twentieth Century',
'Twin City Fire Insurance',
'Unicare',
'Uniguard',
'Union',
'United American',
'United Financial',
'United Fire & Casual',
'United Health Care (also Golden Rule)',
'United Insurance',
'United Pacific Insurance',
'United Security',
'United Services Auto',
'United States Fideli',
'Unitrin',
'Universal Underwriters Insurance',
'US Financial',
'US Health Advisors',
'US Health Group',
'USA Benefits/Continental General',
'USAA',
'USF and G',
'USF&G',
'Utah Home and Fire',
'Utica',
'Vasa North Atlantic',
'Vigilant',
'Viking',
'Vista Health Plan',
'Wawaunesa',
'Wellington',
'Wellpoint',
'West American',
'West Bend Mutual',
'West Field',
'West Plains',
'Western and Southern Life',
'Western Mutual',
'Western National',
'Western Southern Life',
'Westfield',
'William Penn',
'Windsor',
'Windstar',
'Wisconsin Mutual',
'Woodlands Financial Group',
'Workmans Auto',
'World Insurance',
'Worldwide',
'Yellow Key',
'Yosemite',
'Zurich North America',
];

export default CompanyNameList;
